matrix:
  ARCH:
    - linux/amd64

when:
  - event: [push, tag, pull_request]
    branch: [main]
    path:
      include: ['.woodpecker/*.yaml', '*.woodpecker/*.yml', "**/*.rs"]
      exclude: ['*.md', 'docs/**', '*.service', 'advocacy/**']

labels:
  platform: ${ARCH}

steps:
  build:
    image: opensuse/leap
    commands:
      - zypper --non-interactive install rustup openssl-devel libzstd-devel tar gzip
      - rustup default stable
      - rustup install nightly
      - rustup update
      - cargo update
      - cargo build

runs_on: [ success, failure ]
