class Employee {
    val department: Any = "DEFAULT_VALUE_SO_IT_COMPILES."
}

fun findItem(id: String): Nothing {
    TODO("")
}

// class with constructor
class Learning {
    constructor(name: String, age: Int)
    // name & age exists only during construction. and they are not actual field.
}
// currently its only paramters. not properties of the class. you have to assign them to actual properties.

class Learning {
    val name: String
    val age: Int
    constructor(name: String, age: Int) { // sadly val or var cannot be used here.
        // now they are properties.
        this.name = name
        this.age = age
    }
    // becoming props means they get getters (in case of var setters too) generated by the kotlin compiler.
}

// syntax sugar
class Learning constructor(val name: String, val age: Int) // we can use val and var here.
class Learning(val name: String, val age: Int) // even more sugar. however its only optional when we do not need access modifiers.

// all of the above are primary constructors. for secondary, and so on we can just reuse the constructor keyword
class Learning(val name: String, val age: Int) {
    constructor(name: String): this(name, 20)  // secondary
    // all other constructors must delegate to the primary constructor with this() keyword.
    // Kotlin enforces that every secondary constructor must eventually call the primary constructor
    // directly or indirectly.

}

// This discourages constructor overload explosion & pushes you toward default arguments instead. i.e.
class User(val name: String, val age: Int = 0) // this is preferred over secondary constructors.

// if you want to execute code during initalization, use init block.
class User(val name: String, val age: Int) {
    init {
        require(age >= 0) { "Age cannot be negative" }
        println("User created: $name")
    }
}

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

// constructor order of execution:
// -------------------------------
// Primary constructor parameters are passed
// Property initializers run
// init blocks run (top to bottom)
// Secondary constructor body runs (if used)

class Demo(val x: Int) {
    val y = x + 1
    init {
        println("init: $y")
    }
    constructor() : this(10) {
        println("secondary constructor")
    }
}
// lets suppose we call instantiated Demo with no params.
// then, secondary constructor is invoked which delegates to primary constructor.
// then property inits, and then init block then finally secondary constructor's body (`{}`).

// however a better design for such example would be something like this.
class Car(
    val brand: String,
    val model: String = "Unknown",
    val color: String = "Black"
)
// here you can instantiate the class with either all properties, or two or just one.

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

class OOP() {
    fun OOPConcepts() {
        // ACCESS MODIFIERS (Encapsulation)
        // publiс – Accessible to anyone
        // private – Accessible only inside the class
        // protected – Accessible inside the class and its inheritors
        // internal – Accessible in the module

        // access modifiers can be assigned to constructors too.
        class meow private constructor(val id: String)
        // This prevents direct instantiation and is commonly used in factory patterns or singleton-like designs.

        // CLASS:
        // ------
        // class with properties containing default values
        class Student {
            var name = "Lucia"
            var semester = "Fall"
            var gpa = 3.95
        }

        // shorthand syntax without class body
        class Student

        // suppose this as an instance
        class Student {
            var name = "Lucia"
            var semester = "Fall"
            var gpa = 3.95
        }

        fun functo() {
            var student = Student()
            // Instance
            println(student.name)
            // Prints: Lucia
            println(student.semester)
            // Prints: Fall
            println(student.gpa)
            // Prints: 3.95
        }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

        // OPEN CLASS
        // An open class is a class that is allowed to be subclassed.
        // By default, classes in Kotlin are final, meaning they cannot be inherited from.
        // If you want to create a class that other classes can inherit from,
        // you need to mark it as open.
        open class Animal {
            open fun sound() {
                println("Animal makes a sound")
            }
        }

        class Dog : Animal() {
            override fun sound() {
                println("Dog barks")
            }
        }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

        // Explanation:
        // Point class' primary constructor takes two parameters x and y.
        // Two secondary constructors exist, depending upon the type of object
        // passed Point or Circle, the respective constructor is selected.
        // This is called constructor overloading.

        // The first secondary constructor delegates to the primary constructor.
        // // The second secondary constructor delegates to the primary constructor
        // indirectly through the first secondary constructor, assuming the Circle
        // class has a property centre of type Point.

        class Circle(val centre: Point)

        // Constructor delegation ensures that the correct constructor
        // is called based on the type of the argument provided.

        open class Point(val x: Int, val y: Int) {
            constructor(other: Point) : this(other.x, other.y) { /**/ }
            constructor(circle: Circle) : this(circle.centre) { /**/ }
        }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

        // Abstraction vs Encapsulation
        // Abstraction is about what others see and how they interact with an object.
        // Encapsulation is about how an object operates internally and how it responds to messages.

        // ABSTRACTION (INTERFACE & ABSTRACT CLASS)
        // Interfaces cannot have a state.
        // They can only have abstract properties and functions.
        // Cannot have constructors
        interface RegularCat {
            fun pet()
            fun feed(food: Food)
        }

        interface SickCat {
            fun checkStomach()
            fun giveMedicine(pill: Pill)
        }

        // Abstract classes cannot have an instance, but can have real state and constructors.
        // They can have abstract and non-abstract properties and functions
        abstract class RegularCat {
            abstract val name: String
            abstract fun pet()
            abstract fun feed(food: Food)
        }

        abstract class SickCat {
            abstract val location: String
            abstract fun checkStomach()
            fun giveMedicine(pill: Pill) {}
        }

        // INHERITANCE
        // Inheritance is the process of creating a new class from an existing class.
        // The new class is called a subclass, and the existing class is called a superclass.
        // you can inherit only from one class, and from as many interfaces as you like.

        class SickDomesticCat : RegularCat(), CatAtHospital {
            override var isHungry: Boolean = false

            get() = field
            set(value) { /**/ }

            override fun pet() { /**/ }
            override fun feed(food: Food) { /**/ }
            override fun checkStomach() { /**/ }
            override fun giveMedicine(pill: Pill) { /**/ }

            // WHY DO YOU PREVENT A CAT FROM POOPING?
            abstract class Cat {

                // The cat goes through various daily activities.
                fun anotherDay() {
                    // Finds food and digests it.
                    val food = findFood()
                    digest(food)

                    // Finds a place to poop and poops.
                    val whereToPoop = findWhereToPoop()
                    poop(whereToPoop)
                }

                // The cat digests the food.
                private fun digest(food: Food) {
                    println("Digesting food: $food")
                    // After digestion, the cat poops.
                    val whereToPoop = findWhereToPoop()
                    poop(whereToPoop)
                }

                // The cat poops at the given place.
                private fun poop(where: Place): Poop {
                    println("Pooping at: $where")
                    // Create and return a Poop object (implementation is abstracted).
                    return Poop()
                }

                // Abstract methods to be implemented by subclasses.
                abstract fun feed(food: Food)
                abstract fun findWhereToPoop(): Place
                abstract fun findFood(): Food
            }

            // Class representing a Domestic Cat, extending the abstract Cat class.
            class DomesticCat(private val tray: Tray, private val bowl: Bowl) : Cat() {

                // The cat is fed with food, placing it in the bowl.
                override fun feed(food: Food) {
                    println("Feeding the cat with: $food")
                    bowl.addFood(food)
                }

                // The cat finds a place to poop, which is the tray.
                override fun findWhereToPoop(): Place {
                    return tray
                }

                // The cat finds food, either from the bowl or somewhere else.
                override fun findFood(): Food {
                    return bowl.getFood()
                        ?: run {
                            println("Finding food somewhere else")
                            Food() // Implementation of finding food elsewhere.
                        }
                }
            }

            // Dummy classes for illustration purposes.
            class Food {
                override fun toString(): String {
                    return "Food"
                }
            }

            class Place {
                override fun toString(): String {
                    return "Place"
                }
            }

            class Poop

            class Tray : Place() {
                override fun toString(): String {
                    return "Tray"
                }
            }

            class Bowl {
                fun addFood(food: Food) {
                    println("Food added to the bowl: $food")
                }

                fun getFood(): Food? {
                    // Implementation to get food from the bowl (could be null).
                    return null
                }
            }

            fun catPoop() {
                val tray = Tray()
                val bowl = Bowl()
                val domesticCat = DomesticCat(tray, bowl)

                domesticCat.anotherDay() // Simulate a day in the life of the cat.
            }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

            // GETTER, SETTER, PROPERTY, FIELD
            /*___________________________________________________________
            // Properties are declared using var or val keywords.
            // Getter and setter can be defined for a property.
            // Properties can optionally have an initializer, getter, and setter.
            // Use the field keyword to access the values inside the getter or setter,
            // otherwise you might encounter infinite recursion.
            // Properties may have no (backing) filed at all.*/

            class PositiveAttitude(startingAttitude: Int) {
                var attitude = max(0, startingAttitude)
                    set(value) {
                        if (value != 0) {
                            field = value
                        } else {
                            println("Only positive attitude!")
                            field = 0
                        }
                    }

                var hiddenAttitude: Int = startingAttitude
                    private set
                    get() {
                        if (isSecretelyNegative) {
                            println("Don't ask this!")
                            field += 10
                        }
                        return field
                    }

                val isSecretelyNegative: Boolean
                    get() = hiddenAttitude < 0
            }


            // example code
            class LinkedList {
                private var head: Node? = null

                fun add(element: String) {
                    val newNode = Node(element)

                    val it = tail(head)
                    if (it == null) {
                        head = newNode
                    } else {
                        it.next = newNode
                    }
                }

                private fun tail(head: Node?): Node? {
                    var it: Node?

                    it = head
                    while (it?.next != null) {
                        it = it.next
                    }

                    return it
                }

                fun remove(element: String): Boolean {
                    var result = false
                    var previousIt: Node? = null
                    var it: Node? = head
                    while (!result && it != null) {
                        if (0 == element.compareTo(it.data)) {
                            result = true
                            unlink(previousIt, it)
                            break
                        }
                        previousIt = it
                        it = it.next
                    }

                    return result
                }

                private fun unlink(previousIt: Node?, currentIt: Node) {
                    if (currentIt == head) {
                        head = currentIt.next
                    } else {
                        previousIt?.next = currentIt.next
                    }
                }

                fun size(): Int {
                    var size = 0

                    var it = head
                    while (it != null) {
                        ++size
                        it = it.next
                    }

                    return size
                }

                fun get(idx: Int): String {
                    var index = idx
                    var it = head
                    while (index > 0 && it != null) {
                        it = it.next
                        index--
                    }

                    if (it == null) {
                        throw IndexOutOfBoundsException("Index is out of range")
                    }

                    return it.data
                }

                private data class Node(val data: String) {
                    var next: Node? = null
                }
            }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

            // RE: extension function
            fun String.exclaim(): String {
                return this + "!"
            }
            fun operate(a: Int, b: Int, op: (Int, Int) -> Int): Int {
                return op(a, b)
            }
            fun opUser() {
                val res = operate(2, 3)
                println(result)
            }
        }
    }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    // only a single instance exists (Singleton)
    // takes the place of static utility classes
    object Constants {
        const val baseUrl = "http://api.meow.com"
    }

    object Constants {
        // also, const val is allowed inside an object
        const val TIMEOUT = 30_000
    }

    // singleton object that is associated with a class and can hold properties
    // and methods that are accessible without needing an instance of the class.
    // It allows for class-level functionality similar to static members in other
    // languages like Java
    class Configuration {
        companion object {
            // Allowed - inside companion object
            const val API_KEY = "ab12cd34ef56"
        }

        // Not allowed - inside a regular class
        // const val DATABASE = "users" // Error: Const not allowed here
    }

    // usage
    object AppConfig {
        const val API_BASE_URL = "https://api.myservice.com/v1/"
        const val CONNECTION_TIMEOUT = 15_000 // 15 seconds in milliseconds
        const val DEFAULT_PAGE_SIZE = 20
        const val MAX_RETRY_ATTEMPTS = 3
    }
    fun fetchData() {
        println("Connecting to ${AppConfig.API_BASE_URL}")
        println("Timeout set to ${AppConfig.CONNECTION_TIMEOUT}ms")
        // In a real application, these values would be used to configure network requests
    }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    // default values and boundaries
    class UserProfile {
        companion object {
            const val MIN_PASSWORD_LENGTH = 8
            const val MAX_USERNAME_LENGTH = 30
            const val DEFAULT_AVATAR = "default_avatar.png"
        }
        fun validatePassword(password: String): Boolean {
            return password.length >= MIN_PASSWORD_LENGTH
        }
        fun validateUsername(username: String): Boolean {
            return username.isNotEmpty() && username.length <= MAX_USERNAME_LENGTH
        }
    }
    fun main() {
        val profile = UserProfile()
        println("Is 'pass123' a valid password? ${profile.validatePassword("pass123")}")
        println("Is 'thisIsAReallyLongUsernameThatExceedsTheLimit' valid? ${profile.validateUsername("thisIsAReallyLongUsernameThatExceedsTheLimit")}")
    }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    object MathConstants {
        const val PI = 3.14159
        const val E = 2.71828
        const val GOLDEN_RATIO = 1.61803
    }
    fun calculateCircleArea(radius: Double): Double {
        return MathConstants.PI * radius * radius
    }
    fun main() {
        val radius = 5.0
        val area = calculateCircleArea(radius)
        println("The area of a circle with radius $radius is $area")
    }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    class SpaceShip(var name: String, val size: Int) {
        var speed: Int = 0

        fun fly() {
            speed = 100
        }

        fun isFlying(): Boolean {
            return speed > 0
        }

        // companion object replaces static members
        companion object {
            var count: Int = -1 // static variable
            // its only static. no thread safety.
            // opt for
            // val count = AtomicInteger(-1)
            // count.incrementAndGet()
            // and the whole synchronized and stuff.
            fun newSpaceship(): Spaceship {
                return Spaceship("Falcon", 25)
            }
            // to call from java: Spaceship.Companion.newSpaceship()

            @JvmStatic
            fun stringo(): String { // behaves like static method
                return "stringo back to you"
            }
            // to call from java: Spaceship.stringo()

            // for Kotlin both are in same scope.
        }
    }

    val myShip = Spaceship("Enterprise", 150)
    myShip.fly()
    val flying = myShip.isFlying()

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    class Adder {
        operator fun invoke(a: Int, b: Int) = a + b
        //           ^ invoke means the instances can be invoked as function
    }

    val add = Adder()
    println(add(2, 3)) // 5

    class Sailor(var rank: String, var lastName: String) {
        // class properties with accessors
        var fullName: String

        get() = "$rank $lastName"
        set(value) = {
            val (firstWord, remainder) = value.split(" ", limit = 2)
            rank = firstWord
            lastName = remainder
        }
    }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    // RE: subclassing: only open classes can be subclassed
    open class Crewmember(val name: String) {
    // ^ required
        // Only open methods can be overridden
        open fun sayHello() = "Hello, I'm crewmember $name."
    }
    // subclassing
    class Captain(name: String): Crewmemeber(name) {
        override fun sayHello() = "Greetings! I am captain $name."
    }

    // Ideal for holding data. They auto-generate `equals()`, `hasCode()`, `toString()`.

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    // a data class is a structured data container
    // with pre-defined toString() and other overrides
    data class Student(val name: String, var year: Int)
    // name is a read-only property, year is mutable
    val newStudent = Student("Meow", 1)
    // Data class with properties outside the constructor
    data class Professor(val name: String) {
        var isTenured: Boolean = false
    }
    val newProfessor = Professor("Meowser The Great")
    newProfessor.isTenured = true

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    // Enum Classes
    enum class Taste {
        SWEET,
        SOUR,
        SALTY,
        BITTER,
        UMAMI
    }

    val vinegarTaste: Taste = Taste.UMAMI
    // iterating through an enum class
    for (flavor in Taste.values()) {
        print("Taste: ${flavor.ordinal}: ${flavor.name}")
    }

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    // Sealed Classes

    // Restricts class hierarchies and ensures type safety. Useful in when statements.

    // Sealed classes and interfaces provide controlled inheritance of your class hierarchies.
    // All direct subclasses of a sealed class are known at compile time.
    // No other subclasses may appear outside the module and package within which the sealed class is defined.
    // The same logic applies to sealed interfaces and their implementations:
    //     once a module with a sealed interface is compiled, no new implementations can be created.

    // When you combine sealed classes and interfaces with the when expression,
    // you can cover the behavior of all possible subclasses and ensure that no
    // new subclasses are created to affect your code adversely.
    sealed class Error(val message: String) {
        class NetworkError : Error("Network failure")
        class DatabaseError : Error("Database cannot be reached")
        class UnknownError : Error("An unknown error has occurred")
    }

    fun main() {
        val errors = listOf(Error.NetworkError(), Error.DatabaseError(), Error.UnknownError())
        errors.forEach { println(it.message) }
    }
    // Network failure
    // Database cannot be reached
    // An unknown error has occurred

    // useful in enum classes, but can make multiple instances
    sealed class Shape {
        class Circle(val radius: Int): Shape()
        class Square(val sideLength: Int): Shape()
    }
    val circle1 = Shape.Circle(3)
    val circle2 = Shape.Circle(42)
    val square = Shape.Square(5)

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

    sealed class Shape1

    class Circle1(val radius: Double): Shape1()
    class Reactangle1(val width: Double): Shape1()

    fun describe(shape: Shape1) {
        when (shape) {
            is Circle1 -> println("...")
            is Rectangle1 -> println("...")
        }
    }

    fun main() {
        describe(Circle1(4.0))
    }

    sealed class Payment {
        data class CreditCard(val number: String, val expiryDate: String) : Payment()
        data class PayPal(val email: String) : Payment()
        data object Cash : Payment()
    }

    fun processPayment(payment: Payment) {
        when (payment) {
            is Payment.CreditCard -> processCreditCardPayment(payment.number, payment.expiryDate)
            is Payment.PayPal -> processPayPalPayment(payment.email)
            is Payment.Cash -> processCashPayment()
        }
    }
}

//.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-.

// A IRL EXAMPLE:

// Import necessary modules
import io.ktor.server.application.*
import io.ktor.server.resources.*

import kotlinx.serialization.*

// Define the sealed interface for API requests using Ktor resources
@Resource("api")
sealed interface ApiRequest

@Serializable
@Resource("login")
data class LoginRequest(val username: String, val password: String) : ApiRequest

@Serializable
@Resource("logout")
object LogoutRequest : ApiRequest

// Define the ApiResponse sealed class with detailed response types
sealed class ApiResponse {
    data class UserSuccess(val user: UserData) : ApiResponse()
    data object UserNotFound : ApiResponse()
    data class Error(val message: String) : ApiResponse()
}

// User data class to be used in the success response
data class UserData(val userId: String, val name: String, val email: String)

// Function to validate user credentials (for demonstration purposes)
fun isValidUser(username: String, password: String): Boolean {
    // Some validation logic (this is just a placeholder)
    return username == "validUser" && password == "validPass"
}

// Function to handle API requests with detailed responses
fun handleRequest(request: ApiRequest): ApiResponse {
    return when (request) {
        is LoginRequest -> {
            if (isValidUser(request.username, request.password)) {
                ApiResponse.UserSuccess(UserData("userId", "userName", "userEmail"))
            } else {
                ApiResponse.Error("Invalid username or password")
            }
        }
        is LogoutRequest -> {
            // Assuming logout operation always succeeds for this example
            ApiResponse.UserSuccess(UserData("userId", "userName", "userEmail")) // For demonstration
        }
    }
}

// Function to simulate a getUserById call
fun getUserById(userId: String): ApiResponse {
    return if (userId == "validUserId") {
        ApiResponse.UserSuccess(UserData("validUserId", "John Doe", "john@example.com"))
    } else {
        ApiResponse.UserNotFound
    }
    // Error handling would also result in an Error response.
}

// Main function to demonstrate the usage
fun main() {
    val loginResponse = handleRequest(LoginRequest("user", "pass"))
    println(loginResponse)

    val logoutResponse = handleRequest(LogoutRequest)
    println(logoutResponse)

    val userResponse = getUserById("validUserId")
    println(userResponse)

    val userNotFoundResponse = getUserById("invalidId")
    println(userNotFoundResponse)
}


abstract class Base {
    var count: Int = 0
    abstract fun process()
}

// Interfaces
// Interfaces define contracts. They can contain method implementations but cannot hold state.

interface Clickable {
    fun click()
    fun show() = println("Visible")
}

class Button : Clickable {
    override fun click() = println("Clicked")
}

// this is allowed:

interface UserInfo {
    val name: String

    fun printName() {
        println(name)
    }
}

// this is not allowed:

interface Bad {
    var count: Int = 0 // not allowed, no backing field
}

// So interfaces can declare properties, but they cannot store state.

// Inner and Nested Classes

// Nested class (default): does not hold reference to outer class.

// Inner class: holds reference to outer instance.

// two important question are:
// - Does the class automatically see the outer instance?
// - Does the class inherit from the outer class?

class Outer {
    class Nested
    // Nested is independent class
    // has no ref to Outer instance
    // does not inherit from Outer
    // cannot access Outer's properties
}
// can be made like
val n = Outer.Nested() // no Outer object is involved. just logical grouping


class Outer {
    class Nested : Outer()
    // explicitly made Nested inherit from Outer.
    // just inheritance. it does not access to outer instance
    // nested becomes subclass of Outer
    // it has all public/protected members of Outer
    // its own instance of Outer as parent
}
val n = Outer.Nested() // outer instance made and inside it the Nested object


class Outer {
    private val name = "Outer"

    inner class Inner {
        fun print() = println(name)
    }
    // class stores a ref to specific Outer instance
    // it can access private memebers of the Outer instance
}

val outer = Outer()
val Inner = outer.Inner()
// inner keeps ref to that specific outer
// it can access outer.name

// Companion Objects

// Used for static-like behavior. Kotlin does not have static keyword. A companion object is a single object tied to a class.

class User(val name: String) {
    companion object {
        fun create(name: String) = User(name)
    }
}

// accessed as `User.create("Sudan")`

// Under the hood, Kotlin generates something similar to a static holder in Java.

// - The class itself is not an object.
// - The companion object is a singleton object associated with the class.
// - A class describes how to create objects.
// - Object creates exactly one instance.

// it can be named

class User(val name: String) {
    companion object Factory {
        fun create(name: String) = User(name)
    }
}

// can be accessed as `User.Factory`

// Singleton Design Pattern

// use object:

object Database {
    fun connect() = println("Connected")
}

// Lazy Initialization

// Property initialized only when first accessed. Useful for expensive setup.

val config by lazy {
    println("Loading")
    "Config"
}

// `lateinit` & It's Limitation

// Used for non-null mutable properties initialized later.

**Limitations:**

// - Only for var
// - Not for primitive types
// - Must be initialized before access or throws exception
// - Cannot be used with nullable types

lateinit var service: Service


// Visibility Modifier

// - public (default)
// - Private: restricted to its own scope.
// - Protected: visible inside the class and its sub-classes. Not visible outside, even in the same package.
// - Internal: Visible within the same module only. Useful for multi-module projects. A module is usually a Gradle module.

internal class Repo

private fun helper() {  }

// Open Keyword

// Classes and functions are final by default. Use open to allow inheritance.

open class Base
class Child : Base()

final class A // not required. it is final by default.

// however it is needed for explicitly preventing further overriding in
// subclasses of `Child`
open class Base {
    open fun work() {}
}

class Child : Base() {
    final override fun work() {} // <----- here
}

// Reflections

// Allows inspecting classes at runtime. i.e.

// - Class structure
// - Property names
// - Functions
// - Annotations

// can be accessed. in simpler words, the type information not instance information.

class User

val kClass = User::class // User::class gives you a KClass<User> object
                         // that represents metadata about the class at
                         // runtime

println(kClass.simpleName) // prints `User`
println(kClass.qualifiedName) // prints `com.example.User`
