// SPDX-License-Identifier: MIT
// Copyright © 2022 The Tvix Authors
// Copyright © 2025 The Snix Project

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: snix/build/protos/rpc_build.proto

package buildv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_snix_build_protos_rpc_build_proto protoreflect.FileDescriptor

const file_snix_build_protos_rpc_build_proto_rawDesc = "" +
	"\n" +
	"!snix/build/protos/rpc_build.proto\x12\rsnix.build.v1\x1a\x1dsnix/build/protos/build.proto2L\n" +
	"\fBuildService\x12<\n" +
	"\aDoBuild\x12\x1b.snix.build.v1.BuildRequest\x1a\x14.snix.build.v1.BuildB\x1eZ\x1csnix.dev/build/proto;buildv1b\x06proto3"

var file_snix_build_protos_rpc_build_proto_goTypes = []any{
	(*BuildRequest)(nil), // 0: snix.build.v1.BuildRequest
	(*Build)(nil),        // 1: snix.build.v1.Build
}
var file_snix_build_protos_rpc_build_proto_depIdxs = []int32{
	0, // 0: snix.build.v1.BuildService.DoBuild:input_type -> snix.build.v1.BuildRequest
	1, // 1: snix.build.v1.BuildService.DoBuild:output_type -> snix.build.v1.Build
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snix_build_protos_rpc_build_proto_init() }
func file_snix_build_protos_rpc_build_proto_init() {
	if File_snix_build_protos_rpc_build_proto != nil {
		return
	}
	file_snix_build_protos_build_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snix_build_protos_rpc_build_proto_rawDesc), len(file_snix_build_protos_rpc_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snix_build_protos_rpc_build_proto_goTypes,
		DependencyIndexes: file_snix_build_protos_rpc_build_proto_depIdxs,
	}.Build()
	File_snix_build_protos_rpc_build_proto = out.File
	file_snix_build_protos_rpc_build_proto_goTypes = nil
	file_snix_build_protos_rpc_build_proto_depIdxs = nil
}
