on: [push]
jobs:
  check:
    runs-on: guix
    steps:
      - run: git clone --depth=1 --branch=$GITHUB_REF_NAME https://codeberg.org/$GITHUB_REPOSITORY src
      - run: |
          set -e
          ./bootstrap.sh
          ./configure
          make -j${nproc}
          make check -j${nproc}
        shell: guix-ci -Df guix.scm -- {0}
        working-directory: src
  distcheck:
    runs-on: guix
    steps:
      - run: git clone --depth=1 --branch=$GITHUB_REF_NAME https://codeberg.org/$GITHUB_REPOSITORY src
      - run: |
          set -e
          ./bootstrap.sh
          ./configure
          make -j${nproc}
          make distcheck -j${nproc}
        shell: guix-ci -Df guix.scm -- {0}
        working-directory: src
